### ISSUE TITLE
Setting up several of your mods together

### ISSUE THREAD

**Issue by Mynnibauwe** [Woodi-dev/Among-Us-Love-Couple-Mod#7]
Hi !

I'm kind of unexperienced in terms of how mods work, but I wanted to try and merge the Couple Lover Mod with the Sheriff Mod for some games with my friends (and maybe merge some more together in order to have spicy games in the future). But I have no idea how to do that, could you provide a solution (if they are indeed compatible). I have already tried brutally creating a repository with all files from both mods, but as expected since most files share a common name between both mods, it doesn't work.

**Comment by Woodi-dev** [comment]
To start basically you have to create a c# .net standard project and install BepInex bleeding edge.
Then you have to link all .dll files from unhollowed and bepinex core to your project in order to build the mod.
To make the mods work together, update the RPC calls, so they don't overlap. Same issue for patched methods.

**Comment by Mynnibauwe** [comment]
Ok, as a newbie I didn't understand much but I showed this to a friend and he said maybe he'll help me!

Thank you for the help
